site_name: HCW@Home documentation
nav:
  - Home: index.md
  - Deployment concept: deploy.md
  - Install on Debian/Ubuntu: debian.md
  - Install with Docker: docker.md
  - Customize HCW@Home: customize.md
  - Configure with Keycloak: keycloak.md
  - Troubleshooting: troubleshooting.md
theme: readthedocs